title: Sungyoung Lee
description: Undergraduate Student of EECS, Seoul National University
site_title: '@brianlsy - Sungyoung Lee'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: brianlsy
blog_url: https://www.nagekar.com
email: brianlsy@snu.ac.kr
keybase_username: brianlsy
twitter_username: brianlsy_
reddit_username: brianlsy

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 